import { QuestionnaireForm } from "./types"

export const mockQuestionnaires: QuestionnaireForm[] = [
  {
    id: "q-001",
    formCode: "CAT-EMP-2024-001",
    title: "Caterpillar Safety & Operations Assessment",
    description: "Annual employee assessment covering safety protocols, equipment operation, and company policies.",
    department: "Operations",
    timeLimit: 60,
    passingScore: 70,
    isActive: true,
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-20"),
    questions: [
      {
        id: "q1",
        text: "What is the primary purpose of the pre-operation inspection checklist for heavy equipment?",
        type: "multiple-choice",
        required: true,
        points: 10,
        choices: [
          { id: "q1-a", text: "To delay the start of work", isCorrect: false },
          { id: "q1-b", text: "To identify potential safety hazards and equipment issues before operation", isCorrect: true },
          { id: "q1-c", text: "To increase paperwork documentation", isCorrect: false },
          { id: "q1-d", text: "To satisfy regulatory requirements only", isCorrect: false },
        ],
      },
      {
        id: "q2",
        text: "Which of the following are required Personal Protective Equipment (PPE) when operating heavy machinery at CAT facilities? (Select all that apply)",
        type: "checkbox",
        required: true,
        points: 15,
        choices: [
          { id: "q2-a", text: "Hard hat", isCorrect: true },
          { id: "q2-b", text: "Safety glasses", isCorrect: true },
          { id: "q2-c", text: "Steel-toed boots", isCorrect: true },
          { id: "q2-d", text: "High-visibility vest", isCorrect: true },
          { id: "q2-e", text: "Casual footwear", isCorrect: false },
        ],
      },
      {
        id: "q3",
        text: "All Caterpillar employees must complete safety training before operating any heavy equipment.",
        type: "true-false",
        required: true,
        points: 10,
        choices: [
          { id: "q3-a", text: "True", isCorrect: true },
          { id: "q3-b", text: "False", isCorrect: false },
        ],
      },
      {
        id: "q4",
        text: "What is the maximum load capacity (in tons) for a CAT 320 Excavator?",
        type: "short-answer",
        required: true,
        points: 10,
        choices: [],
        correctAnswer: "22",
      },
      {
        id: "q5",
        text: "Describe the proper procedure for reporting a safety incident at a Caterpillar facility. Include the key steps and who should be notified.",
        type: "long-answer",
        required: true,
        points: 20,
        choices: [],
        correctAnswer: "1. Stop work immediately 2. Ensure safety of all personnel 3. Report to immediate supervisor 4. Contact Safety Department 5. Document the incident with photos and written description 6. Cooperate with investigation",
      },
    ],
  },
  {
    id: "q-002",
    formCode: "CAT-HR-2024-001",
    title: "HR Compliance & Policy Assessment",
    description: "Assessment covering company HR policies, workplace conduct, and compliance requirements.",
    department: "Human Resources",
    timeLimit: 45,
    passingScore: 80,
    isActive: true,
    createdAt: new Date("2024-02-01"),
    updatedAt: new Date("2024-02-10"),
    questions: [
      {
        id: "hr-q1",
        text: "What is the maximum number of consecutive days an employee can take as paid vacation without prior approval from department head?",
        type: "multiple-choice",
        required: true,
        points: 10,
        choices: [
          { id: "hr-q1-a", text: "3 days", isCorrect: false },
          { id: "hr-q1-b", text: "5 days", isCorrect: true },
          { id: "hr-q1-c", text: "7 days", isCorrect: false },
          { id: "hr-q1-d", text: "10 days", isCorrect: false },
        ],
      },
      {
        id: "hr-q2",
        text: "Harassment complaints should be reported to HR within 48 hours of the incident.",
        type: "true-false",
        required: true,
        points: 10,
        choices: [
          { id: "hr-q2-a", text: "True", isCorrect: true },
          { id: "hr-q2-b", text: "False", isCorrect: false },
        ],
      },
    ],
  },
  {
    id: "q-003",
    formCode: "CAT-IT-2024-001",
    title: "IT Security Awareness Training",
    description: "Assessment on cybersecurity best practices and IT policies.",
    department: "Information Technology",
    timeLimit: 30,
    passingScore: 75,
    isActive: false,
    createdAt: new Date("2024-03-01"),
    updatedAt: new Date("2024-03-05"),
    questions: [
      {
        id: "it-q1",
        text: "Which of the following are signs of a phishing email? (Select all that apply)",
        type: "checkbox",
        required: true,
        points: 15,
        choices: [
          { id: "it-q1-a", text: "Urgent language demanding immediate action", isCorrect: true },
          { id: "it-q1-b", text: "Suspicious sender email address", isCorrect: true },
          { id: "it-q1-c", text: "Email from your direct manager", isCorrect: false },
          { id: "it-q1-d", text: "Unexpected attachments", isCorrect: true },
        ],
      },
    ],
  },
  {
    id: "q-004",
    formCode: "CAT-MNT-2024-001",
    title: "Equipment Maintenance Certification",
    description: "Certification exam for maintenance technicians covering equipment diagnostics and repair procedures.",
    department: "Maintenance",
    timeLimit: 90,
    passingScore: 85,
    isActive: true,
    createdAt: new Date("2024-01-20"),
    updatedAt: new Date("2024-02-15"),
    questions: [
      {
        id: "mnt-q1",
        text: "What is the recommended interval for hydraulic fluid replacement in CAT machinery?",
        type: "multiple-choice",
        required: true,
        points: 10,
        choices: [
          { id: "mnt-q1-a", text: "Every 500 hours", isCorrect: false },
          { id: "mnt-q1-b", text: "Every 1000 hours", isCorrect: false },
          { id: "mnt-q1-c", text: "Every 2000 hours", isCorrect: true },
          { id: "mnt-q1-d", text: "Every 5000 hours", isCorrect: false },
        ],
      },
    ],
  },
]

// Helper to get a single questionnaire (for backward compatibility)
export const mockQuestionnaire = mockQuestionnaires[0]
