import { ExamSession } from "./types"

// Mock exam sessions data - simulating real-time exam monitoring
export const mockExamSessions: ExamSession[] = [
  {
    id: "session-1",
    formCode: "CAT-EMP-2024-001",
    employeeId: "EMP-001",
    employeeName: "John Anderson",
    department: "Heavy Equipment Operations",
    status: "in_progress",
    startTime: new Date(Date.now() - 15 * 60 * 1000), // Started 15 mins ago
    violations: [
      {
        id: "v1",
        type: "tab_switch",
        timestamp: new Date(Date.now() - 10 * 60 * 1000),
        description: "Switched to another browser tab",
      },
      {
        id: "v2",
        type: "window_blur",
        timestamp: new Date(Date.now() - 5 * 60 * 1000),
        description: "Clicked outside the exam window",
      },
    ],
    answers: {},
  },
  {
    id: "session-2",
    formCode: "CAT-EMP-2024-001",
    employeeId: "EMP-002",
    employeeName: "Sarah Mitchell",
    department: "Safety Compliance",
    status: "in_progress",
    startTime: new Date(Date.now() - 20 * 60 * 1000), // Started 20 mins ago
    violations: [],
    answers: {},
  },
  {
    id: "session-3",
    formCode: "CAT-EMP-2024-001",
    employeeId: "EMP-003",
    employeeName: "Michael Chen",
    department: "Heavy Equipment Operations",
    status: "terminated",
    startTime: new Date(Date.now() - 25 * 60 * 1000),
    endTime: new Date(Date.now() - 10 * 60 * 1000),
    violations: [
      {
        id: "v3",
        type: "tab_switch",
        timestamp: new Date(Date.now() - 22 * 60 * 1000),
        description: "Switched to another browser tab",
      },
      {
        id: "v4",
        type: "tab_switch",
        timestamp: new Date(Date.now() - 18 * 60 * 1000),
        description: "Switched to another browser tab",
      },
      {
        id: "v5",
        type: "window_blur",
        timestamp: new Date(Date.now() - 12 * 60 * 1000),
        description: "Clicked outside the exam window",
      },
    ],
    score: 0,
    totalPoints: 25,
    passed: false,
    answers: {},
  },
  {
    id: "session-4",
    formCode: "CAT-EMP-2024-001",
    employeeId: "EMP-004",
    employeeName: "Emily Rodriguez",
    department: "Maintenance",
    status: "completed",
    startTime: new Date(Date.now() - 45 * 60 * 1000),
    endTime: new Date(Date.now() - 15 * 60 * 1000),
    violations: [],
    score: 23,
    totalPoints: 25,
    passed: true,
    answers: {},
  },
  {
    id: "session-5",
    formCode: "CAT-EMP-2024-001",
    employeeId: "EMP-005",
    employeeName: "David Kim",
    department: "Heavy Equipment Operations",
    status: "completed",
    startTime: new Date(Date.now() - 50 * 60 * 1000),
    endTime: new Date(Date.now() - 25 * 60 * 1000),
    violations: [
      {
        id: "v6",
        type: "tab_switch",
        timestamp: new Date(Date.now() - 40 * 60 * 1000),
        description: "Switched to another browser tab",
      },
    ],
    score: 20,
    totalPoints: 25,
    passed: true,
    answers: {},
  },
]
